remote_theme: noew/academic
title: Katherine A. Moos
author: Katherine A. Moos
description: Assistant Professor in Economics at the University of Massachusetts Amherst

baseurl: ""
url: "http://www.katherinemoos.com"

# Author

email: kmoos@umass.edu
github_username: profmoos
author_website: http://www.katherinemoos.com
curriculum:
  name: curriculum vitae
  url: https://umass-my.sharepoint.com/:b:/g/personal/kmoos_umass_edu/EagrcBdtmMRBlKENNjYJRR4BWdD7sk5YuzDqszDQOKgE8Q?e=hNyxum
