remote_theme: noew/academic
title: Katherine A. Moos
author: Katherine A. Moos
description: Associate Professor in Economics at the University of Massachusetts Amherst

baseurl: ""
url: "http://www.katherinemoos.com"

# Author

email: kmoos@umass.edu
github_username: profmoos
author_website: http://www.katherinemoos.com
curriculum:
  name: curriculum vitae
  url: KMOOS_CV_Current.pdf
